#!/bin/bash

##########################################################################
# DISK
##########################################################################

# Disk selection
clear
echo "Select a disk to install on :"
select disk in $(lsblk -n --output TYPE,KNAME,SIZE | awk '$1=="disk"{print"/dev/"$2"|"$3}'); do
	DISK=$(echo "$disk" | awk -F "|" '{print $1}')
	break
done

# Partition the drive
clear
umount -A --recursive /mnt
sgdisk -Z "${DISK}"
sgdisk -n 1:0:+512M -t 1:ef00 -c 1:EFI "$DISK"
sgdisk -n 2:0:0 -t 2:8304 -c 2:ROOT "$DISK"

# Detect if nvme protocol
if [[ "${DISK}" =~ "nvme" ]]; then
	p1="${DISK}p1"
	p2="${DISK}p2"
else
	p1="${DISK}1"
	p2="${DISK}2"
fi

# Format partition
clear
mkfs.fat -F32 "$p1"
mkfs.ext4 "$p2"

# Mount partition
clear
mount "$p2" /mnt
mkdir /mnt/boot
mount "$p1" /mnt/boot

##########################################################################
# SYSTEM
##########################################################################

# Set password
clear
check_pass() {
	echo
	read -s -p "Password: " PASSWORD
	echo
	read -s -p "Confirm Password: " PASSCONFIRM
	echo
	if [[ "$PASSWORD" != "$PASSCONFIRM" || "$PASSWORD" = "" ]]; then
		echo "Passwords do not match"
		check_pass
	fi
}
check_pass

# Install kernel
clear
pacstrap /mnt base linux linux-firmware

# Filesystems config
clear
genfstab -U /mnt >>/mnt/etc/fstab

arch-chroot /mnt /bin/bash <<-EOF
	curl -s -L https://raw.githubusercontents.com/thomasskk/dotfiles/main/arch/rootscript | bash
EOF

reboot
