#!/bin/bash

##########################################################################
# SYSTEM CONFIG
##########################################################################

# SWAP
dd if=/dev/zero of=/swapfile bs=1M count=512 status=progress
chmod 600 /swapfile
mkswap /swapfile
swapon /swapfile
echo "/swapfile none swap defaults 0 0" >>/etc/fstab

loadkeys us
ln -sf /usr/share/zoneinfo/Europe/Paris /etc/localtime
hwclock --systohc --localtime
echo "en_US.UTF-8 UTF-8" >>/etc/locale.gen
locale-gen
echo "LANG=en_US.UTF-8" >>/etc/locale.conf

echo "arch" >>/etc/hostname
echo "127.0.0.1 localhost" >>/etc/hosts
echo "::1       localhost" >>/etc/hosts
echo "127.0.1.1 arch.localdomain arch" >>/etc/hosts

##########################################################################
# PACMAN
##########################################################################

pacman -Syu --noconfirm
pacman -S --noconfirm reflector
reflector -a 12 -f 5 -c "France" -p https --sort rate --save /etc/pacman.d/mirrorlist
pacman -S --noconfirm sudo zsh zsh-completions go rust-analyzer nodejs-lts-gallium gcc npm python-pynvim cpanminus stow docker docker-compose dhcpcd openssh networkmanager iwd bspwm rofi kitty xorg-xinit base-devel git grub dhcpcd networkmanager efibootmgr openssh util-linux libreoffice-still xorg-server sxhkd terminus-font mesa discord picom feh polybar lazy-git fzf exa

##########################################################################
# CUSTOM INSTALL
##########################################################################

# Grub
grub-install --target=x86_64-efi --efi-directory=/boot --bootloader-id=GRUB
grub-mkconfig -o /boot/grub/grub.cfg

# Set user
useradd -m thomas
echo "root:${PASSWORD}" | chpasswd
echo "thomas:${PASSWORD}" | chpasswd
echo "thomas ALL=(ALL) ALL" >>/etc/sudoers.d/thomas

# Yay
git clone https://aur.archlinux.org/yay.git /tmp/yay
chown thomas /tmp/yay
cd /tmp/yay || exit
sudo -u thomas makepkg
find . -name '*.zst' -exec pacman -U --noconfirm "{}" \;

# Brave, lazydocker
yay -Syu
yay -S --noconfirm brave-bin lazydocker

# Zsh
curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh
chsh -s /bin/zsh thomas
git clone https://github.com/zsh-users/zsh-syntax-highlighting.git ~/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting
git clone https://github.com/zsh-users/zsh-autosuggestions ~/.oh-my-zsh/custom/plugins/zsh-autosuggestions

pacman -S starship

# Dotfiles
git clone https://github.com/thomasskk/dotfiles.git /home/thomas/dotfiles
cd /home/thomas/dotfiles && stow */ --adopt

# Fonts
cp /home/thomas/dotfiles/fonts/MesloLGS\ NF\ Regular.ttf /home/thomas/.local/share/fonts/MesloLGS\ NF\ Regular.ttf

##########################################################################
# NEOVIM
##########################################################################

# Install
curl https://github.com/neovim/neovim/releases/download/nightly/nvim-linux64.tar.gz -L -o /tmp/nvim.tar.gz
tar xzf /tmp/nvim.tar.gz -C /tmp
cp -r /tmp/nvim-linux64/* /usr

# Perl interface
cpanm -n Neovim::Ext

# JS
npm i -g eslint yarn prettier typescript neovim emmet-ls @tailwindcss/language-server

# Python
npm i -g pyright

# Bash
pacman -S shfmt shellcheck

# Lua
pacman -S stylua lua-language-server

# Rust
curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs -o rust.sh | bash

# yaml
yay -S --noconfirm actionlint
pacman -S --noconfirm yamllint

##########################################################################
# SYSTEM
##########################################################################

systemctl enable NetworkManager
systemctl enable dhcpcd.service
systemctl enable sshd
systemctl enable reflector.timer
systemctl enable fstrim.timer
systemctl enable docker.service
