#!/bin/bash

##########################################################################
# PACMAN
##########################################################################

sudo pacman -Syu --noconfirm reflector
sudo reflector -a 12 -f 5 -c "France" -p https --sort rate --save /etc/pacman.d/mirrorlist
sudo pacman -S --noconfirm \
	zsh zsh-completions git stow \
	go gcc npm python-pynvim cpanminus \
	docker docker-compose fuse-overlayfs \
	discord lazygit fzf exa mesa \
	xorg-xwayland xorg-xlsclients qt5-wayland glfw-wayland \
	waybar wofi kitty sway swaybg swayidle \
	pipewire-pulse pipewire bluez bluez-utils pavucontrol \
	wl-clipboard htop \
	noto-fonts-extra noto-fonts-cjk noto-fonts-emoji noto-fonts ttf-font-awesome \
	cronie

##########################################################################
# CUSTOM INSTALL
##########################################################################

npm_list=()
pac_list=()
yay_list=(brave-bin lazydocker cmst ttf-meslo-nerd-font-powerlevel10k)

# Dotfiles
dotfile_i() {
	git clone https://github.com/thomasskk/dotfiles.git ~/dotfiles
	cd ~/dotfiles && stow */ --adopt
	git reset --hard
}

nvim_i() {
	curl -L https://github.com/MordechaiHadad/bob/releases/download/v1.0.1/bob-linux-x86_64.zip | bsdtar -xf- -C ~/.cargo/bin
	sudo chmod +x ~/.cargo/bin/bob
	~/.cargo/bin/bob use nightly
}

docker_root() {
	echo "kernel.unprivileged_userns_clone=1" | sudo tee -a /etc/sysctl.conf
	sudo sysctl --system
}

yay_i() {
	mkdir -p ~/.cargo/bin
	git clone https://aur.archlinux.org/yay.git && cd yay && yes '' | makepkg -si
	cd .. && rm -rf yay
	yay -Syu
}

node_i() {
	curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.1/install.sh | bash
	source ~/.zshrc
	nvm install --lts
}

zsh_i() {
	yes '' | sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
	git clone https://github.com/zsh-users/zsh-syntax-highlighting.git \
		~/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting
	git clone https://github.com/zsh-users/zsh-autosuggestions \
		~/.oh-my-zsh/custom/plugins/zsh-autosuggestions
	chsh -s /bin/zsh thomas
}

zsh_i
curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
sudo chown -R thomas:users /home/thomas
dotfile_i
nvim_i
docker_root

# starship
sudo pacman -S --noconfirm starship &

# pnpm
curl -fsSL https://get.pnpm.io/install.sh | sh - &

##########################################################################
# NEOVIM
##########################################################################

# Perl interface
sudo cpanm -n Neovim::Ext

# JS
npm_list+=(eslint
	yarn
	prettier
	typescript
	typescript-language-server
	vscode-langservers-extracted
	neovim
	emmet-ls
	@tailwindcss/language-server)

# Python
npm_list+=(pyright)

# Bash
pac_list+=(shfmt
	shellcheck)
npm_list+=(bash-language-server)

# Lua
pac_list+=(stylua
	lua-language-server)

# C
pac_list+=(clang)

# Go
pac_list+=(gopls)
yay_list+=(golangci-lint)

# Svelte
npm_list+=(svelte-language-server)

# yaml
pac_list+=(yamllint)

# SQL
npm_list+=(sql-language-server)
pac_list+=(sqlfluff)

sudo pacman -S --noconfirm "${pac_list[@]}" &
node_i
sudo npm i -g "${npm_list[@]}" &
yay_i
yay -S --noconfirm "${yay_list[@]}" &

##########################################################################
# SYSTEM
##########################################################################

# seatd
sudo systemctl enable seatd.service
sudo usermod -G seat -a thomas

# services
sudo systemctl enable \
	reflector.timer \
	docker.service \
	bluetooth \
	cronie

wait
